name: Build APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Checkout SFML
      uses: actions/checkout@v2
      with:
        repository: 'SFML/SFML'
        path: './SFML'

    - name: Configure cmake SFML
      run: cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=$ANDROID_NDK_LATEST_HOME -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Debug -B./SFML/.build ./SFML

    - name: Build SFML
      run: cmake --build ./SFML/.build --config=Debug

    - name: Install SFML
      run: cmake --install ./SFML/.build --config=Debug

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.5

    - name: Gradle build
      run: gradle build

    - name: Upload apk-debug
      uses: actions/upload-artifact@v2
      with:
        name: apk-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk
