name: Build APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Checkout SFML
      uses: actions/checkout@v2
      with:
        repository: 'SFML/SFML'
        path: './SFML'

    - name: Configure cmake SFML
      run: cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_INSTALL_PREFIX=".libs-temp/sfml" -DCMAKE_ANDROID_NDK=$ANDROID_NDK_LATEST_HOME -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Debug -B./SFML/.build ./SFML

    - name: Build & install SFML
      run: cmake --build ./SFML/.build --config=Debug --target=install

    - name: Checkout box2d
      uses: actions/checkout@v2
      with:
        repository: 'erincatto/box2d'
        path: './box2d'

      # path to box2d install ".libs-temp/box2d"
    - name: Configure cmake box2d
      run: cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_INSTALL_PREFIX=".libs-temp/box2d" -DCMAKE_ANDROID_NDK=$ANDROID_NDK_LATEST_HOME -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Debug -B./box2d/.build ./box2d

    - name: Build & install box2d
      run: cmake --build ./box2d/.build --config=Debug --target=install

    - name: Copy box2d Android.mk
      run: mkdir -p .libs-temp/box2d && cp android/hacks/box2d-android.mk .libs-temp/box2d/Android.mk

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.2.1

    - name: Gradle build
      run: gradle build

    - name: Upload apk-debug
      uses: actions/upload-artifact@v2
      with:
        name: apk-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk
