name: Run clang-format

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Check clang-format version
      run: clang-format --version

    - name: Run clang-format
      run: find . -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" | xargs -I {} clang-format -i {} -n --verbose --Werror
